# Generated by Django 5.2.3 on 2025-06-11 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کالکشن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کالکشن',
                'verbose_name_plural': 'کالکشن\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محیط')),
                ('variables', models.JSONField(default=dict, verbose_name='متغیرها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'محیط',
                'verbose_name_plural': 'محیط\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام درخواست')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10, verbose_name='متد')),
                ('url', models.URLField(max_length=2000, verbose_name='آدرس URL')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('headers', models.JSONField(default=dict, verbose_name='هدرها')),
                ('params', models.JSONField(default=dict, verbose_name='پارامترها')),
                ('auth_type', models.CharField(blank=True, max_length=50, verbose_name='نوع احراز هویت')),
                ('auth_data', models.JSONField(default=dict, verbose_name='داده\u200cهای احراز هویت')),
                ('body_type', models.CharField(choices=[('none', 'None'), ('form-data', 'Form Data'), ('x-www-form-urlencoded', 'URL Encoded'), ('raw', 'Raw'), ('binary', 'Binary')], default='none', max_length=30, verbose_name='نوع بدنه')),
                ('body_raw', models.TextField(blank=True, verbose_name='متن خام')),
                ('body_raw_type', models.CharField(choices=[('text', 'Text'), ('json', 'JSON'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('xml', 'XML')], default='text', max_length=20, verbose_name='نوع متن خام')),
                ('body_form_data', models.JSONField(default=dict, verbose_name='داده\u200cهای فرم')),
                ('body_urlencoded', models.JSONField(default=dict, verbose_name='داده\u200cهای URL Encoded')),
                ('timeout', models.IntegerField(default=30, verbose_name='تایم اوت (ثانیه)')),
                ('follow_redirects', models.BooleanField(default=True, verbose_name='دنبال کردن ریدایرکت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.collection', verbose_name='کالکشن')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.environment', verbose_name='محیط')),
            ],
            options={
                'verbose_name': 'درخواست API',
                'verbose_name_plural': 'درخواست\u200cهای API',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='متد')),
                ('url', models.URLField(max_length=2000, verbose_name='آدرس URL')),
                ('headers', models.JSONField(default=dict, verbose_name='هدرها')),
                ('body', models.TextField(blank=True, verbose_name='بدنه درخواست')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='کد وضعیت')),
                ('response_headers', models.JSONField(default=dict, verbose_name='هدرهای پاسخ')),
                ('response_body', models.TextField(blank=True, verbose_name='بدنه پاسخ')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='زمان پاسخ (ثانیه)')),
                ('response_size', models.IntegerField(blank=True, null=True, verbose_name='اندازه پاسخ (بایت)')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20, verbose_name='وضعیت')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان اجرا')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.apirequest', verbose_name='درخواست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه درخواست',
                'verbose_name_plural': 'تاریخچه درخواست\u200cها',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام پاسخ')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ذخیره')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.requesthistory', verbose_name='تاریخچه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ ذخیره شده',
                'verbose_name_plural': 'پاسخ\u200cهای ذخیره شده',
                'ordering': ['-created_at'],
            },
        ),
    ]
